export const ROUTES = {
  home: "/",
  pay: "/pay",
  exchange: "/exchange",
  rwa: "/rwa",
  payPricing: "/pay/pricing",
  payPartnerProgram: "/pay/partner-program",
  payFaq: "/pay/faq",
  payAboutUs: "/pay/about-us",
  aboutUs: "/about-us",
  privacyPolicy: "/privacy-policy",
  termsOfUse: "/terms-of-use",
  amlPolicy: "/aml-policy",
  cookiePolicy: "/cookie-policy",
} as const;
