name: 🚦 Test changes

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master, prod]

concurrency:
  group: pr-ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-packages:
    name: 📦 Build packages
    runs-on: [self-hosted, ubuntu-arm-2204-kuna]
    steps:
      - name: 🛒 Checkout changes
        uses: actions/checkout@v4

      - name: 🛠️ Setup environment
        uses: ./.github/actions/setup

      - name: 📥 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🛠️ Build packages
        run: pnpm run build

  run-tests:
    name: 🧪 Run tests
    needs: build-packages
    runs-on: [self-hosted, ubuntu-arm-2204-kuna]
    steps:
      - name: 🛒 Checkout changes
        uses: actions/checkout@v4

      - name: 🛠️ Setup environment
        uses: ./.github/actions/setup

      - name: 📥 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🏃 Run tests
        run: pnpm run test
